print("#########################")
print("#                       #")
print("#    M.Fahreza Fahma    #")
print("#    1610817210016      #")
print("#                       #")
print("#########################")
